title: Synergy Department Website
email: you@email.arizona.edu
description: > # this means to ignore newlines until "baseurl:"
  Teaching generic business subjects including value-added strategy, synthesizing
  cross-functional data, and meshing efficient imperatives.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://syn.arizona.edu" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
